/* ====================================
File name: exerc_2_7.c (or cpp)
Date: 2021-02-04
Group nr 14
Members that contribute to the solutions: Krasen Parvanov, Chrysostomos Tsagkidis, Eemil Jeskanen
Member not present at demonstration time: N/A
Demonstration code: 5202
====================================== */

// Include section
#include <string.h>
#include <stdlib.h>
#include "stdio.h"
#include "ctype.h"

// Define section
#define SIZE_PERSONAL_NUMBER 10 // define size of personal number in format yymmddxxxx
#define SIZE_USER_INPUT 64 // accepted size of user input
#define CORRECT_NUMBER_MESSAGE "You entered a valid personal number.\n" // String to be printed when a valid personal number was received
#define WRONG_NUMBER_MESSAGE "You entered an invalid personal number.\n" // String to be printed when an invalid personal number was received
#define WRONG_PARAMETERS_MESSAGE "The number you entered was not in format <yymmddxxxx>\n" // String to be printed when the given input does not follow the personal number format
#define PROMP_INPUT_MESSAGE "Enter a personal number in format <yymmddxxxx>. To exit the program enter <q>\n" // Initial prompt message to the user
#define EXIT_MESSAGE "Thank you for using the application.\n" // String to be printed when exiting the application
#define EXIT_CHAR 'q' // Character for exiting the program
#define TRUE 1      // Define true
#define FALSE 0     // Define false
#define JANUARY 1   // Value representing January
#define FEBRUARY 2  // Value representing February
#define MARCH 3     // Value representing March
#define MAY 5       // Value representing May
#define JULY 7      // Value representing July
#define AUGUST 8    // Value representing August
#define OCTOBER 10  // Value representing October
#define DECEMBER 12 // Value representing December

/* ==================================== Main program section ====================================== */
/* This program reads a swedish personal number and verifies that the control digit is corresponding
 * to the one generated by the Luhn Algorithm. It also verifies whether the user provided a valid date.
 * It even considers leap years ;-) After the verification the program prints the result and prompts
 * the user to check another personal number.
 * */

// Function declaration

int readPersnr(char *person); // Used to read user input
int controlDigit( const char * persnr); // check if the last digit of a given number is valid
int controlDate(char *person); // used to check if the date is valid
int inputValidationInteger(char *input); // checks if the input was integer numbers
int checkLeapYear(int year); // check if a given year is leap
int getIntegerValue(char c); // convert a char to integer


int main() {
    // Variable declarations and initialization
    char *personalNumber = calloc(SIZE_PERSONAL_NUMBER, sizeof(char)); // Create pointer and allocate memory to store the personal number
    int keepReading = FALSE; // boolean to control the main loop

    keepReading = readPersnr(personalNumber); // call function to read user input
    // Main loop the loop runs while the user doesn't input "q" than the read method returns false and the loop is terminated
    while (keepReading) {
        if(controlDate(personalNumber)) { // call method to verify that the number contains a valid year-month-day in the first 6 positions
            if (controlDigit(personalNumber)) { // call method to check if the last digit is a valid control digit
                printf(CORRECT_NUMBER_MESSAGE); // if valid confirm
            } else {
                printf(WRONG_NUMBER_MESSAGE); // if control digit is wrong notify user
            }
        } else { // if not a valid date print wrong number message to user
            printf(WRONG_NUMBER_MESSAGE);
        }
        keepReading = readPersnr(personalNumber); // call function to continue reading personal number from user again
    }
    free(personalNumber); // free the memory that has been allocated to storing the personal number
    printf(EXIT_MESSAGE); // Print goodbye message
    return 0; // Exit the program
}

//----------Functions Section------------

// function used to read user input. The function keeps asking for input until it doesn't get 10 integer numbers
int readPersnr(char *person) {
    printf(PROMP_INPUT_MESSAGE); // ask user for input
    char input[SIZE_USER_INPUT]; // store input
    fgets(input,SIZE_USER_INPUT, stdin); // read input from buffer and store it in the array
    if(input[0] == EXIT_CHAR && strlen(input) == 2 ){ // check if the user has entered exit_char
        return FALSE; // return false when exit char is received in order to terminate the main loop
    }else if(strlen(input) != SIZE_PERSONAL_NUMBER + 1 || !inputValidationInteger(input)) { // if the user has not entered valid amount of char
                                                                                            // call method to verify if it's integer input
                                                                                            // if the method returns false(not integers present in array)
        printf(WRONG_PARAMETERS_MESSAGE);                                                   // notify user for wrong input
        
      return readPersnr(person);                                                            // use recursion to keep reading input
    }else { // Else input is right size and all integers
        strcpy(person, input); // copy input from the array into the main store array
        return TRUE; // return true to main - keeps the main loop running
    }
}
// Function to validate if a given string consists of only integers
int inputValidationInteger(char *input) {
    while (*input) { // loop in the array using the pointer
        if(*input != '\n') { // ignore the end of line for the comparison
            if (isdigit(*input) == 0) { // check if the char is not digit isdigit function
                return FALSE; // if not digit return false
            }
        }
        input++; // increment the pointer
    }
    return TRUE; // if the loop run without encountering char return true
}

// Function to validate if the date part of the provided personal number is correct
int controlDate(char *person) {
    // Variable declarations
    int year, month, day; // Store the corresponding year, month and day part based on the provided 6 first digits
    long personalNumber; // Store the personal number using a numeric format
    char *pointer; // pointer needed for the strtol function (the pointer stores the non numeric part of the char array that is to be converted)

    personalNumber = (long) strtol(person, &pointer, 10); // Converting the char array to a base(10) long variable for storing the personal number, using strtol()

    year = (int) (personalNumber / 100000000) % 100; // Casting the first two digits of the provided personal number (long) to an int variable to get the year
    month = (int) (personalNumber / 1000000) % 100; // Casting the 3rd and 4th digits of the provided personal number (long) to an int variable to get the month
    day = (int) (personalNumber / 10000) % 100; // Casting the 5th and 6th digits of the provided personal number (long) to an int variable to get the day

    if ((month > 0 && month <= 12)) { // Check if the month is within a valid interval
        if(month == JANUARY || month == MARCH ||month == MAY ||month == JULY || month == AUGUST || month == OCTOBER || month == DECEMBER) { // Covers the months that have 31 days
            if (day > 0 && day <= 31) { // Check if the day is within the valid interval
                return TRUE; // return true for a valid date
            }
        } else { // Covers all the months that have either 30 days or less
            if ( month == FEBRUARY) { // Covers the case of February
                if (!checkLeapYear(year)) { // Check if the year is not a leap year
                    if (day > 0 && day <= 28) { // Check if the day is within the valid interval
                        return TRUE; // return true for a valid date
                    }
                } else { // Covers the leap year case for February
                    if (day > 0 && day <= 29) { // Check if the day is within the valid interval
                        return TRUE; // return true for a valid date
                    }
                }
            } else { // Covers the months that have 30 days
                if (day > 0 && day <= 30) { // Check if the day is within the valid interval
                    return TRUE; // return true for a valid date
                }
            }
        }
    }

    return FALSE; // Return false for invalid date
}

// Function to calculate if the provided year is a leap year
int checkLeapYear(int year) {

    if (((year % 4 == 0) && (year % 100!= 0)) || (year % 400 == 0)) { // Check if the year follows the leap year calculation pattern
        return TRUE; // return true if it is a leap year
    }

    return FALSE; // return false if it is not a leap year
}

// Function to validate if the control digit of the provided personal number is correct
int controlDigit(const char *persnr) {

    int i; // index for the loop
    long totalSum = 0; // Store the total sum of the sums of digits
    long sumOfNumber = 0; // Store the multiplied value of the corresponding digit
    long firstDigitOfTheSumOfNumber = 0; // Store the first digit of the sum of number when the sumOfNumber is larger than 9
    long secondDigitOfTheSumOfNumber = 0; // Store the second digit of the sum of number when the sumOfNumber is larger than 9

    for (i = 0; i < SIZE_PERSONAL_NUMBER - 1; i++){ // iterate through the personal number's characters
        if (i % 2 == 0) { // If its an even position in the array
            sumOfNumber = getIntegerValue(persnr[i]) * 2; // Get integer value of the corresponding char multiplied by 2
            if (sumOfNumber > 9){ // If the resulted number is greater than 9
                firstDigitOfTheSumOfNumber = (sumOfNumber / 10) % 10; // get the first digit of the sum of number
                secondDigitOfTheSumOfNumber = sumOfNumber % 10; // get the second digit of the sum of number
                totalSum += firstDigitOfTheSumOfNumber + secondDigitOfTheSumOfNumber; // add to the totalSum the sum of the two numbers
            } else { // If the resulted number is less or equal than 9
                totalSum += (sumOfNumber); // add the number to the totalSum
            }
        } else { // If its an odd position in the array
            totalSum += getIntegerValue(persnr[i]); // getting the integer value of the currect character in the array and adding it to the totalSum
        }
    }

    if (((10 - (totalSum % 10)) % 10) == getIntegerValue(persnr[SIZE_PERSONAL_NUMBER - 1])) { // Compare the last digit of the subtraction between 10 minus the last digit of the total sum
                                                                                                 // to the last digit of the provided personal number
        return TRUE; // return true if the control digit is correct
    }

    return FALSE; // return false if the control digit is incorrect
}

// Function for converting a given char to integer and returning the int
int getIntegerValue(char c) {
    int num = 0; // define the int to be return
    num = c - '0'; // subtract '0' from entered char to get the corresponding integer
    return num; // return the integer
}
